package com.whty.cms.network.pojo;

public class ApplyInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.user_id
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.user_name
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.user_email
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.device_name
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private String deviceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.device_use
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private String deviceUse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.oper_os
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private String operOs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.device_mac
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private String deviceMac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.device_type
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private String deviceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_info.unti_time
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	private String untiTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.user_id
	 * @return  the value of apply_info.user_id
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.user_id
	 * @param userId  the value for apply_info.user_id
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.user_name
	 * @return  the value of apply_info.user_name
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.user_name
	 * @param userName  the value for apply_info.user_name
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.user_email
	 * @return  the value of apply_info.user_email
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.user_email
	 * @param userEmail  the value for apply_info.user_email
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail == null ? null : userEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.device_name
	 * @return  the value of apply_info.device_name
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public String getDeviceName() {
		return deviceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.device_name
	 * @param deviceName  the value for apply_info.device_name
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName == null ? null : deviceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.device_use
	 * @return  the value of apply_info.device_use
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public String getDeviceUse() {
		return deviceUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.device_use
	 * @param deviceUse  the value for apply_info.device_use
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setDeviceUse(String deviceUse) {
		this.deviceUse = deviceUse == null ? null : deviceUse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.oper_os
	 * @return  the value of apply_info.oper_os
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public String getOperOs() {
		return operOs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.oper_os
	 * @param operOs  the value for apply_info.oper_os
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setOperOs(String operOs) {
		this.operOs = operOs == null ? null : operOs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.device_mac
	 * @return  the value of apply_info.device_mac
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public String getDeviceMac() {
		return deviceMac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.device_mac
	 * @param deviceMac  the value for apply_info.device_mac
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setDeviceMac(String deviceMac) {
		this.deviceMac = deviceMac == null ? null : deviceMac.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.device_type
	 * @return  the value of apply_info.device_type
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public String getDeviceType() {
		return deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.device_type
	 * @param deviceType  the value for apply_info.device_type
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType == null ? null : deviceType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_info.unti_time
	 * @return  the value of apply_info.unti_time
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public String getUntiTime() {
		return untiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_info.unti_time
	 * @param untiTime  the value for apply_info.unti_time
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	public void setUntiTime(String untiTime) {
		this.untiTime = untiTime == null ? null : untiTime.trim();
	}
}