package com.whty.cms.network.pojo;

public class Cable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cable.cable_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private Integer cableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cable.cable_name
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private String cableName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cable.switch_port__id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private Integer switchPortId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cable.is_use
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private String isUse;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cable.cable_id
	 * @return  the value of cable.cable_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Integer getCableId() {
		return cableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cable.cable_id
	 * @param cableId  the value for cable.cable_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setCableId(Integer cableId) {
		this.cableId = cableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cable.cable_name
	 * @return  the value of cable.cable_name
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getCableName() {
		return cableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cable.cable_name
	 * @param cableName  the value for cable.cable_name
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setCableName(String cableName) {
		this.cableName = cableName == null ? null : cableName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cable.switch_port__id
	 * @return  the value of cable.switch_port__id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Integer getSwitchPortId() {
		return switchPortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cable.switch_port__id
	 * @param switchPortId  the value for cable.switch_port__id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setSwitchPortId(Integer switchPortId) {
		this.switchPortId = switchPortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cable.is_use
	 * @return  the value of cable.is_use
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getIsUse() {
		return isUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cable.is_use
	 * @param isUse  the value for cable.is_use
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setIsUse(String isUse) {
		this.isUse = isUse == null ? null : isUse.trim();
	}
}