package com.whty.cms.network.pojo;

public class Device {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.device_id
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	private String deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.user_id
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.device_name
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	private String deviceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.device_type
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	private String deviceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.device_os
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	private String deviceOs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.device_flag
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	private String deviceFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.auth_stat
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	private String authStat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.device_purpose
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	private String devicePurpose;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.device_id
	 * @return  the value of device.device_id
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public String getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.device_id
	 * @param deviceId  the value for device.device_id
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId == null ? null : deviceId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.user_id
	 * @return  the value of device.user_id
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.user_id
	 * @param userId  the value for device.user_id
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.device_name
	 * @return  the value of device.device_name
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public String getDeviceName() {
		return deviceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.device_name
	 * @param deviceName  the value for device.device_name
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName == null ? null : deviceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.device_type
	 * @return  the value of device.device_type
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public String getDeviceType() {
		return deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.device_type
	 * @param deviceType  the value for device.device_type
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType == null ? null : deviceType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.device_os
	 * @return  the value of device.device_os
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public String getDeviceOs() {
		return deviceOs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.device_os
	 * @param deviceOs  the value for device.device_os
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public void setDeviceOs(String deviceOs) {
		this.deviceOs = deviceOs == null ? null : deviceOs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.device_flag
	 * @return  the value of device.device_flag
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public String getDeviceFlag() {
		return deviceFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.device_flag
	 * @param deviceFlag  the value for device.device_flag
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public void setDeviceFlag(String deviceFlag) {
		this.deviceFlag = deviceFlag == null ? null : deviceFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.auth_stat
	 * @return  the value of device.auth_stat
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public String getAuthStat() {
		return authStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.auth_stat
	 * @param authStat  the value for device.auth_stat
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public void setAuthStat(String authStat) {
		this.authStat = authStat == null ? null : authStat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.device_purpose
	 * @return  the value of device.device_purpose
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public String getDevicePurpose() {
		return devicePurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.device_purpose
	 * @param devicePurpose  the value for device.device_purpose
	 * @mbggenerated  Mon Aug 24 17:15:41 CST 2015
	 */
	public void setDevicePurpose(String devicePurpose) {
		this.devicePurpose = devicePurpose == null ? null : devicePurpose
				.trim();
	}
}