package com.whty.cms.network.pojo;

import java.util.Date;

public class NetworkAdapter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.networkadapter_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String networkadapterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.networkadapter_type
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String networkadapterType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.networkadapter_mac
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String networkadapterMac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.device_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.cable_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String cableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.conference_code
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String conferenceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.ip
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.deadline
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private Date deadline;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.networkadapter_id
	 * @return  the value of networkadapter.networkadapter_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getNetworkadapterId() {
		return networkadapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.networkadapter_id
	 * @param networkadapterId  the value for networkadapter.networkadapter_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setNetworkadapterId(String networkadapterId) {
		this.networkadapterId = networkadapterId == null ? null
				: networkadapterId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.networkadapter_type
	 * @return  the value of networkadapter.networkadapter_type
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getNetworkadapterType() {
		return networkadapterType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.networkadapter_type
	 * @param networkadapterType  the value for networkadapter.networkadapter_type
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setNetworkadapterType(String networkadapterType) {
		this.networkadapterType = networkadapterType == null ? null
				: networkadapterType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.networkadapter_mac
	 * @return  the value of networkadapter.networkadapter_mac
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getNetworkadapterMac() {
		return networkadapterMac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.networkadapter_mac
	 * @param networkadapterMac  the value for networkadapter.networkadapter_mac
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setNetworkadapterMac(String networkadapterMac) {
		this.networkadapterMac = networkadapterMac == null ? null
				: networkadapterMac.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.device_id
	 * @return  the value of networkadapter.device_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.device_id
	 * @param deviceId  the value for networkadapter.device_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId == null ? null : deviceId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.cable_id
	 * @return  the value of networkadapter.cable_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getCableId() {
		return cableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.cable_id
	 * @param cableId  the value for networkadapter.cable_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setCableId(String cableId) {
		this.cableId = cableId == null ? null : cableId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.conference_code
	 * @return  the value of networkadapter.conference_code
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getConferenceCode() {
		return conferenceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.conference_code
	 * @param conferenceCode  the value for networkadapter.conference_code
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setConferenceCode(String conferenceCode) {
		this.conferenceCode = conferenceCode == null ? null : conferenceCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.ip
	 * @return  the value of networkadapter.ip
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.ip
	 * @param ip  the value for networkadapter.ip
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.deadline
	 * @return  the value of networkadapter.deadline
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Date getDeadline() {
		return deadline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.deadline
	 * @param deadline  the value for networkadapter.deadline
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}
}