package com.whty.cms.network.pojo;

import java.util.Date;

public class NetworkAdapter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.networkadapter_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private Integer networkadapterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.networkadapter_type
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private Integer networkadapterType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.networkadapter_mac
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private String networkadapterMac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.device_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private Integer deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.cable_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private Integer cableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.conference_code
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private String conferenceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.ip
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column networkadapter.deadline
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private Date deadline;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.networkadapter_id
	 * @return  the value of networkadapter.networkadapter_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Integer getNetworkadapterId() {
		return networkadapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.networkadapter_id
	 * @param networkadapterId  the value for networkadapter.networkadapter_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setNetworkadapterId(Integer networkadapterId) {
		this.networkadapterId = networkadapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.networkadapter_type
	 * @return  the value of networkadapter.networkadapter_type
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Integer getNetworkadapterType() {
		return networkadapterType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.networkadapter_type
	 * @param networkadapterType  the value for networkadapter.networkadapter_type
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setNetworkadapterType(Integer networkadapterType) {
		this.networkadapterType = networkadapterType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.networkadapter_mac
	 * @return  the value of networkadapter.networkadapter_mac
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getNetworkadapterMac() {
		return networkadapterMac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.networkadapter_mac
	 * @param networkadapterMac  the value for networkadapter.networkadapter_mac
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setNetworkadapterMac(String networkadapterMac) {
		this.networkadapterMac = networkadapterMac == null ? null
				: networkadapterMac.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.device_id
	 * @return  the value of networkadapter.device_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Integer getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.device_id
	 * @param deviceId  the value for networkadapter.device_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.cable_id
	 * @return  the value of networkadapter.cable_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Integer getCableId() {
		return cableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.cable_id
	 * @param cableId  the value for networkadapter.cable_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setCableId(Integer cableId) {
		this.cableId = cableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.conference_code
	 * @return  the value of networkadapter.conference_code
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getConferenceCode() {
		return conferenceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.conference_code
	 * @param conferenceCode  the value for networkadapter.conference_code
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setConferenceCode(String conferenceCode) {
		this.conferenceCode = conferenceCode == null ? null : conferenceCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.ip
	 * @return  the value of networkadapter.ip
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.ip
	 * @param ip  the value for networkadapter.ip
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column networkadapter.deadline
	 * @return  the value of networkadapter.deadline
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Date getDeadline() {
		return deadline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column networkadapter.deadline
	 * @param deadline  the value for networkadapter.deadline
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}
}