package com.whty.cms.network.pojo;

public class SwitchPort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switchport.switch_port_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Integer switchPortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switchport.switch_port
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private String switchPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switchport.vlan_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Integer vlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switchport.switch_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Integer switchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switchport.port_desc
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private String portDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switchport.status
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switchport.limit_speed
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Double limitSpeed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switchport.switch_port_id
     *
     * @return the value of switchport.switch_port_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Integer getSwitchPortId() {
        return switchPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switchport.switch_port_id
     *
     * @param switchPortId the value for switchport.switch_port_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setSwitchPortId(Integer switchPortId) {
        this.switchPortId = switchPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switchport.switch_port
     *
     * @return the value of switchport.switch_port
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public String getSwitchPort() {
        return switchPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switchport.switch_port
     *
     * @param switchPort the value for switchport.switch_port
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setSwitchPort(String switchPort) {
        this.switchPort = switchPort == null ? null : switchPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switchport.vlan_id
     *
     * @return the value of switchport.vlan_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Integer getVlanId() {
        return vlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switchport.vlan_id
     *
     * @param vlanId the value for switchport.vlan_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setVlanId(Integer vlanId) {
        this.vlanId = vlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switchport.switch_id
     *
     * @return the value of switchport.switch_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Integer getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switchport.switch_id
     *
     * @param switchId the value for switchport.switch_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setSwitchId(Integer switchId) {
        this.switchId = switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switchport.port_desc
     *
     * @return the value of switchport.port_desc
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public String getPortDesc() {
        return portDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switchport.port_desc
     *
     * @param portDesc the value for switchport.port_desc
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setPortDesc(String portDesc) {
        this.portDesc = portDesc == null ? null : portDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switchport.status
     *
     * @return the value of switchport.status
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switchport.status
     *
     * @param status the value for switchport.status
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switchport.limit_speed
     *
     * @return the value of switchport.limit_speed
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Double getLimitSpeed() {
        return limitSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switchport.limit_speed
     *
     * @param limitSpeed the value for switchport.limit_speed
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setLimitSpeed(Double limitSpeed) {
        this.limitSpeed = limitSpeed;
    }
}