package com.whty.cms.network.pojo;

import java.util.ArrayList;
import java.util.List;

public class SwitchExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public SwitchExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSwitchIdIsNull() {
			addCriterion("switch_id is null");
			return (Criteria) this;
		}

		public Criteria andSwitchIdIsNotNull() {
			addCriterion("switch_id is not null");
			return (Criteria) this;
		}

		public Criteria andSwitchIdEqualTo(Integer value) {
			addCriterion("switch_id =", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdNotEqualTo(Integer value) {
			addCriterion("switch_id <>", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdGreaterThan(Integer value) {
			addCriterion("switch_id >", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("switch_id >=", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdLessThan(Integer value) {
			addCriterion("switch_id <", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdLessThanOrEqualTo(Integer value) {
			addCriterion("switch_id <=", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdIn(List<Integer> values) {
			addCriterion("switch_id in", values, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdNotIn(List<Integer> values) {
			addCriterion("switch_id not in", values, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdBetween(Integer value1, Integer value2) {
			addCriterion("switch_id between", value1, value2, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdNotBetween(Integer value1, Integer value2) {
			addCriterion("switch_id not between", value1, value2, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchNameIsNull() {
			addCriterion("switch_name is null");
			return (Criteria) this;
		}

		public Criteria andSwitchNameIsNotNull() {
			addCriterion("switch_name is not null");
			return (Criteria) this;
		}

		public Criteria andSwitchNameEqualTo(String value) {
			addCriterion("switch_name =", value, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameNotEqualTo(String value) {
			addCriterion("switch_name <>", value, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameGreaterThan(String value) {
			addCriterion("switch_name >", value, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameGreaterThanOrEqualTo(String value) {
			addCriterion("switch_name >=", value, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameLessThan(String value) {
			addCriterion("switch_name <", value, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameLessThanOrEqualTo(String value) {
			addCriterion("switch_name <=", value, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameLike(String value) {
			addCriterion("switch_name like", value, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameNotLike(String value) {
			addCriterion("switch_name not like", value, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameIn(List<String> values) {
			addCriterion("switch_name in", values, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameNotIn(List<String> values) {
			addCriterion("switch_name not in", values, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameBetween(String value1, String value2) {
			addCriterion("switch_name between", value1, value2, "switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchNameNotBetween(String value1, String value2) {
			addCriterion("switch_name not between", value1, value2,
					"switchName");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeIsNull() {
			addCriterion("switch_type is null");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeIsNotNull() {
			addCriterion("switch_type is not null");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeEqualTo(Integer value) {
			addCriterion("switch_type =", value, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeNotEqualTo(Integer value) {
			addCriterion("switch_type <>", value, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeGreaterThan(Integer value) {
			addCriterion("switch_type >", value, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("switch_type >=", value, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeLessThan(Integer value) {
			addCriterion("switch_type <", value, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeLessThanOrEqualTo(Integer value) {
			addCriterion("switch_type <=", value, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeIn(List<Integer> values) {
			addCriterion("switch_type in", values, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeNotIn(List<Integer> values) {
			addCriterion("switch_type not in", values, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeBetween(Integer value1, Integer value2) {
			addCriterion("switch_type between", value1, value2, "switchType");
			return (Criteria) this;
		}

		public Criteria andSwitchTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("switch_type not between", value1, value2,
					"switchType");
			return (Criteria) this;
		}

		public Criteria andManagementIpIsNull() {
			addCriterion("management_ip is null");
			return (Criteria) this;
		}

		public Criteria andManagementIpIsNotNull() {
			addCriterion("management_ip is not null");
			return (Criteria) this;
		}

		public Criteria andManagementIpEqualTo(String value) {
			addCriterion("management_ip =", value, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpNotEqualTo(String value) {
			addCriterion("management_ip <>", value, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpGreaterThan(String value) {
			addCriterion("management_ip >", value, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpGreaterThanOrEqualTo(String value) {
			addCriterion("management_ip >=", value, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpLessThan(String value) {
			addCriterion("management_ip <", value, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpLessThanOrEqualTo(String value) {
			addCriterion("management_ip <=", value, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpLike(String value) {
			addCriterion("management_ip like", value, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpNotLike(String value) {
			addCriterion("management_ip not like", value, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpIn(List<String> values) {
			addCriterion("management_ip in", values, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpNotIn(List<String> values) {
			addCriterion("management_ip not in", values, "managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpBetween(String value1, String value2) {
			addCriterion("management_ip between", value1, value2,
					"managementIp");
			return (Criteria) this;
		}

		public Criteria andManagementIpNotBetween(String value1, String value2) {
			addCriterion("management_ip not between", value1, value2,
					"managementIp");
			return (Criteria) this;
		}

		public Criteria andLocationIdIsNull() {
			addCriterion("location_id is null");
			return (Criteria) this;
		}

		public Criteria andLocationIdIsNotNull() {
			addCriterion("location_id is not null");
			return (Criteria) this;
		}

		public Criteria andLocationIdEqualTo(Integer value) {
			addCriterion("location_id =", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdNotEqualTo(Integer value) {
			addCriterion("location_id <>", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdGreaterThan(Integer value) {
			addCriterion("location_id >", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("location_id >=", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdLessThan(Integer value) {
			addCriterion("location_id <", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdLessThanOrEqualTo(Integer value) {
			addCriterion("location_id <=", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdIn(List<Integer> values) {
			addCriterion("location_id in", values, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdNotIn(List<Integer> values) {
			addCriterion("location_id not in", values, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdBetween(Integer value1, Integer value2) {
			addCriterion("location_id between", value1, value2, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdNotBetween(Integer value1, Integer value2) {
			addCriterion("location_id not between", value1, value2,
					"locationId");
			return (Criteria) this;
		}

		public Criteria andPortNumIsNull() {
			addCriterion("port_num is null");
			return (Criteria) this;
		}

		public Criteria andPortNumIsNotNull() {
			addCriterion("port_num is not null");
			return (Criteria) this;
		}

		public Criteria andPortNumEqualTo(Integer value) {
			addCriterion("port_num =", value, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumNotEqualTo(Integer value) {
			addCriterion("port_num <>", value, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumGreaterThan(Integer value) {
			addCriterion("port_num >", value, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("port_num >=", value, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumLessThan(Integer value) {
			addCriterion("port_num <", value, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumLessThanOrEqualTo(Integer value) {
			addCriterion("port_num <=", value, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumIn(List<Integer> values) {
			addCriterion("port_num in", values, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumNotIn(List<Integer> values) {
			addCriterion("port_num not in", values, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumBetween(Integer value1, Integer value2) {
			addCriterion("port_num between", value1, value2, "portNum");
			return (Criteria) this;
		}

		public Criteria andPortNumNotBetween(Integer value1, Integer value2) {
			addCriterion("port_num not between", value1, value2, "portNum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table switch
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 29 14:45:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}