package com.whty.cms.network.pojo;

public class SwitchPort {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switchport.switch_port_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String switchPortId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switchport.switch_port
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String switchPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switchport.vlan_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String vlanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switchport.switch_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String switchId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switchport.port_desc
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String portDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switchport.status
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switchport.limit_speed
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private Double limitSpeed;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switchport.switch_port_id
	 * @return  the value of switchport.switch_port_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getSwitchPortId() {
		return switchPortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switchport.switch_port_id
	 * @param switchPortId  the value for switchport.switch_port_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setSwitchPortId(String switchPortId) {
		this.switchPortId = switchPortId == null ? null : switchPortId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switchport.switch_port
	 * @return  the value of switchport.switch_port
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getSwitchPort() {
		return switchPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switchport.switch_port
	 * @param switchPort  the value for switchport.switch_port
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setSwitchPort(String switchPort) {
		this.switchPort = switchPort == null ? null : switchPort.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switchport.vlan_id
	 * @return  the value of switchport.vlan_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getVlanId() {
		return vlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switchport.vlan_id
	 * @param vlanId  the value for switchport.vlan_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setVlanId(String vlanId) {
		this.vlanId = vlanId == null ? null : vlanId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switchport.switch_id
	 * @return  the value of switchport.switch_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getSwitchId() {
		return switchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switchport.switch_id
	 * @param switchId  the value for switchport.switch_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setSwitchId(String switchId) {
		this.switchId = switchId == null ? null : switchId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switchport.port_desc
	 * @return  the value of switchport.port_desc
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getPortDesc() {
		return portDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switchport.port_desc
	 * @param portDesc  the value for switchport.port_desc
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setPortDesc(String portDesc) {
		this.portDesc = portDesc == null ? null : portDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switchport.status
	 * @return  the value of switchport.status
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switchport.status
	 * @param status  the value for switchport.status
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switchport.limit_speed
	 * @return  the value of switchport.limit_speed
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Double getLimitSpeed() {
		return limitSpeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switchport.limit_speed
	 * @param limitSpeed  the value for switchport.limit_speed
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setLimitSpeed(Double limitSpeed) {
		this.limitSpeed = limitSpeed;
	}
}