package com.whty.cms.network.pojo;

public class Switch {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switch.switch_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String switchId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switch.switch_name
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String switchName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switch.switch_type
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String switchType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switch.management_ip
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private String managementIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switch.location_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private Integer locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column switch.port_num
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	private Integer portNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switch.switch_id
	 * @return  the value of switch.switch_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getSwitchId() {
		return switchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switch.switch_id
	 * @param switchId  the value for switch.switch_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setSwitchId(String switchId) {
		this.switchId = switchId == null ? null : switchId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switch.switch_name
	 * @return  the value of switch.switch_name
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getSwitchName() {
		return switchName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switch.switch_name
	 * @param switchName  the value for switch.switch_name
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setSwitchName(String switchName) {
		this.switchName = switchName == null ? null : switchName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switch.switch_type
	 * @return  the value of switch.switch_type
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getSwitchType() {
		return switchType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switch.switch_type
	 * @param switchType  the value for switch.switch_type
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setSwitchType(String switchType) {
		this.switchType = switchType == null ? null : switchType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switch.management_ip
	 * @return  the value of switch.management_ip
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getManagementIp() {
		return managementIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switch.management_ip
	 * @param managementIp  the value for switch.management_ip
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setManagementIp(String managementIp) {
		this.managementIp = managementIp == null ? null : managementIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switch.location_id
	 * @return  the value of switch.location_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switch.location_id
	 * @param locationId  the value for switch.location_id
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column switch.port_num
	 * @return  the value of switch.port_num
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Integer getPortNum() {
		return portNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column switch.port_num
	 * @param portNum  the value for switch.port_num
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setPortNum(Integer portNum) {
		this.portNum = portNum;
	}
}