package com.whty.cms.network.pojo;

public class Switch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.switch_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Integer switchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.switch_name
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private String switchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.switch_type
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Integer switchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.management_ip
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private String managementIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.location_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.port_num
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    private Integer portNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.switch_id
     *
     * @return the value of switch.switch_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Integer getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.switch_id
     *
     * @param switchId the value for switch.switch_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setSwitchId(Integer switchId) {
        this.switchId = switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.switch_name
     *
     * @return the value of switch.switch_name
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public String getSwitchName() {
        return switchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.switch_name
     *
     * @param switchName the value for switch.switch_name
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setSwitchName(String switchName) {
        this.switchName = switchName == null ? null : switchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.switch_type
     *
     * @return the value of switch.switch_type
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Integer getSwitchType() {
        return switchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.switch_type
     *
     * @param switchType the value for switch.switch_type
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setSwitchType(Integer switchType) {
        this.switchType = switchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.management_ip
     *
     * @return the value of switch.management_ip
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public String getManagementIp() {
        return managementIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.management_ip
     *
     * @param managementIp the value for switch.management_ip
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setManagementIp(String managementIp) {
        this.managementIp = managementIp == null ? null : managementIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.location_id
     *
     * @return the value of switch.location_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.location_id
     *
     * @param locationId the value for switch.location_id
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.port_num
     *
     * @return the value of switch.port_num
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public Integer getPortNum() {
        return portNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.port_num
     *
     * @param portNum the value for switch.port_num
     *
     * @mbggenerated Wed Jul 29 14:45:13 CST 2015
     */
    public void setPortNum(Integer portNum) {
        this.portNum = portNum;
    }
}