package com.whty.cms.network.pojo;

import java.util.ArrayList;
import java.util.List;

public class SwitchPortExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public SwitchPortExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSwitchPortIdIsNull() {
			addCriterion("switch_port_id is null");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdIsNotNull() {
			addCriterion("switch_port_id is not null");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdEqualTo(String value) {
			addCriterion("switch_port_id =", value, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdNotEqualTo(String value) {
			addCriterion("switch_port_id <>", value, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdGreaterThan(String value) {
			addCriterion("switch_port_id >", value, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdGreaterThanOrEqualTo(String value) {
			addCriterion("switch_port_id >=", value, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdLessThan(String value) {
			addCriterion("switch_port_id <", value, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdLessThanOrEqualTo(String value) {
			addCriterion("switch_port_id <=", value, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdLike(String value) {
			addCriterion("switch_port_id like", value, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdNotLike(String value) {
			addCriterion("switch_port_id not like", value, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdIn(List<String> values) {
			addCriterion("switch_port_id in", values, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdNotIn(List<String> values) {
			addCriterion("switch_port_id not in", values, "switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdBetween(String value1, String value2) {
			addCriterion("switch_port_id between", value1, value2,
					"switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIdNotBetween(String value1, String value2) {
			addCriterion("switch_port_id not between", value1, value2,
					"switchPortId");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIsNull() {
			addCriterion("switch_port is null");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIsNotNull() {
			addCriterion("switch_port is not null");
			return (Criteria) this;
		}

		public Criteria andSwitchPortEqualTo(String value) {
			addCriterion("switch_port =", value, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortNotEqualTo(String value) {
			addCriterion("switch_port <>", value, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortGreaterThan(String value) {
			addCriterion("switch_port >", value, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortGreaterThanOrEqualTo(String value) {
			addCriterion("switch_port >=", value, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortLessThan(String value) {
			addCriterion("switch_port <", value, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortLessThanOrEqualTo(String value) {
			addCriterion("switch_port <=", value, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortLike(String value) {
			addCriterion("switch_port like", value, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortNotLike(String value) {
			addCriterion("switch_port not like", value, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortIn(List<String> values) {
			addCriterion("switch_port in", values, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortNotIn(List<String> values) {
			addCriterion("switch_port not in", values, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortBetween(String value1, String value2) {
			addCriterion("switch_port between", value1, value2, "switchPort");
			return (Criteria) this;
		}

		public Criteria andSwitchPortNotBetween(String value1, String value2) {
			addCriterion("switch_port not between", value1, value2,
					"switchPort");
			return (Criteria) this;
		}

		public Criteria andVlanIdIsNull() {
			addCriterion("vlan_id is null");
			return (Criteria) this;
		}

		public Criteria andVlanIdIsNotNull() {
			addCriterion("vlan_id is not null");
			return (Criteria) this;
		}

		public Criteria andVlanIdEqualTo(String value) {
			addCriterion("vlan_id =", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdNotEqualTo(String value) {
			addCriterion("vlan_id <>", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdGreaterThan(String value) {
			addCriterion("vlan_id >", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdGreaterThanOrEqualTo(String value) {
			addCriterion("vlan_id >=", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdLessThan(String value) {
			addCriterion("vlan_id <", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdLessThanOrEqualTo(String value) {
			addCriterion("vlan_id <=", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdLike(String value) {
			addCriterion("vlan_id like", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdNotLike(String value) {
			addCriterion("vlan_id not like", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdIn(List<String> values) {
			addCriterion("vlan_id in", values, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdNotIn(List<String> values) {
			addCriterion("vlan_id not in", values, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdBetween(String value1, String value2) {
			addCriterion("vlan_id between", value1, value2, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdNotBetween(String value1, String value2) {
			addCriterion("vlan_id not between", value1, value2, "vlanId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdIsNull() {
			addCriterion("switch_id is null");
			return (Criteria) this;
		}

		public Criteria andSwitchIdIsNotNull() {
			addCriterion("switch_id is not null");
			return (Criteria) this;
		}

		public Criteria andSwitchIdEqualTo(String value) {
			addCriterion("switch_id =", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdNotEqualTo(String value) {
			addCriterion("switch_id <>", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdGreaterThan(String value) {
			addCriterion("switch_id >", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdGreaterThanOrEqualTo(String value) {
			addCriterion("switch_id >=", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdLessThan(String value) {
			addCriterion("switch_id <", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdLessThanOrEqualTo(String value) {
			addCriterion("switch_id <=", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdLike(String value) {
			addCriterion("switch_id like", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdNotLike(String value) {
			addCriterion("switch_id not like", value, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdIn(List<String> values) {
			addCriterion("switch_id in", values, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdNotIn(List<String> values) {
			addCriterion("switch_id not in", values, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdBetween(String value1, String value2) {
			addCriterion("switch_id between", value1, value2, "switchId");
			return (Criteria) this;
		}

		public Criteria andSwitchIdNotBetween(String value1, String value2) {
			addCriterion("switch_id not between", value1, value2, "switchId");
			return (Criteria) this;
		}

		public Criteria andPortDescIsNull() {
			addCriterion("port_desc is null");
			return (Criteria) this;
		}

		public Criteria andPortDescIsNotNull() {
			addCriterion("port_desc is not null");
			return (Criteria) this;
		}

		public Criteria andPortDescEqualTo(String value) {
			addCriterion("port_desc =", value, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescNotEqualTo(String value) {
			addCriterion("port_desc <>", value, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescGreaterThan(String value) {
			addCriterion("port_desc >", value, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescGreaterThanOrEqualTo(String value) {
			addCriterion("port_desc >=", value, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescLessThan(String value) {
			addCriterion("port_desc <", value, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescLessThanOrEqualTo(String value) {
			addCriterion("port_desc <=", value, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescLike(String value) {
			addCriterion("port_desc like", value, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescNotLike(String value) {
			addCriterion("port_desc not like", value, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescIn(List<String> values) {
			addCriterion("port_desc in", values, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescNotIn(List<String> values) {
			addCriterion("port_desc not in", values, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescBetween(String value1, String value2) {
			addCriterion("port_desc between", value1, value2, "portDesc");
			return (Criteria) this;
		}

		public Criteria andPortDescNotBetween(String value1, String value2) {
			addCriterion("port_desc not between", value1, value2, "portDesc");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedIsNull() {
			addCriterion("limit_speed is null");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedIsNotNull() {
			addCriterion("limit_speed is not null");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedEqualTo(Double value) {
			addCriterion("limit_speed =", value, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedNotEqualTo(Double value) {
			addCriterion("limit_speed <>", value, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedGreaterThan(Double value) {
			addCriterion("limit_speed >", value, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedGreaterThanOrEqualTo(Double value) {
			addCriterion("limit_speed >=", value, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedLessThan(Double value) {
			addCriterion("limit_speed <", value, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedLessThanOrEqualTo(Double value) {
			addCriterion("limit_speed <=", value, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedIn(List<Double> values) {
			addCriterion("limit_speed in", values, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedNotIn(List<Double> values) {
			addCriterion("limit_speed not in", values, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedBetween(Double value1, Double value2) {
			addCriterion("limit_speed between", value1, value2, "limitSpeed");
			return (Criteria) this;
		}

		public Criteria andLimitSpeedNotBetween(Double value1, Double value2) {
			addCriterion("limit_speed not between", value1, value2,
					"limitSpeed");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table switchport
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table switchport
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 29 14:45:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}