package com.whty.cms.network.pojo;

public class Vlan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vlan.vlan_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private Integer vlanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vlan.vlan_name
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private String vlanName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vlan.vlan_desc
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private String vlanDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vlan.ip_section
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	private String ipSection;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vlan.vlan_id
	 * @return  the value of vlan.vlan_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public Integer getVlanId() {
		return vlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vlan.vlan_id
	 * @param vlanId  the value for vlan.vlan_id
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setVlanId(Integer vlanId) {
		this.vlanId = vlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vlan.vlan_name
	 * @return  the value of vlan.vlan_name
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getVlanName() {
		return vlanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vlan.vlan_name
	 * @param vlanName  the value for vlan.vlan_name
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setVlanName(String vlanName) {
		this.vlanName = vlanName == null ? null : vlanName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vlan.vlan_desc
	 * @return  the value of vlan.vlan_desc
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getVlanDesc() {
		return vlanDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vlan.vlan_desc
	 * @param vlanDesc  the value for vlan.vlan_desc
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setVlanDesc(String vlanDesc) {
		this.vlanDesc = vlanDesc == null ? null : vlanDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vlan.ip_section
	 * @return  the value of vlan.ip_section
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public String getIpSection() {
		return ipSection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vlan.ip_section
	 * @param ipSection  the value for vlan.ip_section
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	public void setIpSection(String ipSection) {
		this.ipSection = ipSection == null ? null : ipSection.trim();
	}
}