package com.whty.cms.network.pojo;

import java.util.ArrayList;
import java.util.List;

public class VlanExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public VlanExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andVlanIdIsNull() {
			addCriterion("vlan_id is null");
			return (Criteria) this;
		}

		public Criteria andVlanIdIsNotNull() {
			addCriterion("vlan_id is not null");
			return (Criteria) this;
		}

		public Criteria andVlanIdEqualTo(String value) {
			addCriterion("vlan_id =", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdNotEqualTo(String value) {
			addCriterion("vlan_id <>", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdGreaterThan(String value) {
			addCriterion("vlan_id >", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdGreaterThanOrEqualTo(String value) {
			addCriterion("vlan_id >=", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdLessThan(String value) {
			addCriterion("vlan_id <", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdLessThanOrEqualTo(String value) {
			addCriterion("vlan_id <=", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdLike(String value) {
			addCriterion("vlan_id like", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdNotLike(String value) {
			addCriterion("vlan_id not like", value, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdIn(List<String> values) {
			addCriterion("vlan_id in", values, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdNotIn(List<String> values) {
			addCriterion("vlan_id not in", values, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdBetween(String value1, String value2) {
			addCriterion("vlan_id between", value1, value2, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanIdNotBetween(String value1, String value2) {
			addCriterion("vlan_id not between", value1, value2, "vlanId");
			return (Criteria) this;
		}

		public Criteria andVlanNameIsNull() {
			addCriterion("vlan_name is null");
			return (Criteria) this;
		}

		public Criteria andVlanNameIsNotNull() {
			addCriterion("vlan_name is not null");
			return (Criteria) this;
		}

		public Criteria andVlanNameEqualTo(String value) {
			addCriterion("vlan_name =", value, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameNotEqualTo(String value) {
			addCriterion("vlan_name <>", value, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameGreaterThan(String value) {
			addCriterion("vlan_name >", value, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameGreaterThanOrEqualTo(String value) {
			addCriterion("vlan_name >=", value, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameLessThan(String value) {
			addCriterion("vlan_name <", value, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameLessThanOrEqualTo(String value) {
			addCriterion("vlan_name <=", value, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameLike(String value) {
			addCriterion("vlan_name like", value, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameNotLike(String value) {
			addCriterion("vlan_name not like", value, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameIn(List<String> values) {
			addCriterion("vlan_name in", values, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameNotIn(List<String> values) {
			addCriterion("vlan_name not in", values, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameBetween(String value1, String value2) {
			addCriterion("vlan_name between", value1, value2, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanNameNotBetween(String value1, String value2) {
			addCriterion("vlan_name not between", value1, value2, "vlanName");
			return (Criteria) this;
		}

		public Criteria andVlanDescIsNull() {
			addCriterion("vlan_desc is null");
			return (Criteria) this;
		}

		public Criteria andVlanDescIsNotNull() {
			addCriterion("vlan_desc is not null");
			return (Criteria) this;
		}

		public Criteria andVlanDescEqualTo(String value) {
			addCriterion("vlan_desc =", value, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescNotEqualTo(String value) {
			addCriterion("vlan_desc <>", value, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescGreaterThan(String value) {
			addCriterion("vlan_desc >", value, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescGreaterThanOrEqualTo(String value) {
			addCriterion("vlan_desc >=", value, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescLessThan(String value) {
			addCriterion("vlan_desc <", value, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescLessThanOrEqualTo(String value) {
			addCriterion("vlan_desc <=", value, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescLike(String value) {
			addCriterion("vlan_desc like", value, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescNotLike(String value) {
			addCriterion("vlan_desc not like", value, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescIn(List<String> values) {
			addCriterion("vlan_desc in", values, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescNotIn(List<String> values) {
			addCriterion("vlan_desc not in", values, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescBetween(String value1, String value2) {
			addCriterion("vlan_desc between", value1, value2, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andVlanDescNotBetween(String value1, String value2) {
			addCriterion("vlan_desc not between", value1, value2, "vlanDesc");
			return (Criteria) this;
		}

		public Criteria andIpSectionIsNull() {
			addCriterion("ip_section is null");
			return (Criteria) this;
		}

		public Criteria andIpSectionIsNotNull() {
			addCriterion("ip_section is not null");
			return (Criteria) this;
		}

		public Criteria andIpSectionEqualTo(String value) {
			addCriterion("ip_section =", value, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionNotEqualTo(String value) {
			addCriterion("ip_section <>", value, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionGreaterThan(String value) {
			addCriterion("ip_section >", value, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionGreaterThanOrEqualTo(String value) {
			addCriterion("ip_section >=", value, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionLessThan(String value) {
			addCriterion("ip_section <", value, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionLessThanOrEqualTo(String value) {
			addCriterion("ip_section <=", value, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionLike(String value) {
			addCriterion("ip_section like", value, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionNotLike(String value) {
			addCriterion("ip_section not like", value, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionIn(List<String> values) {
			addCriterion("ip_section in", values, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionNotIn(List<String> values) {
			addCriterion("ip_section not in", values, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionBetween(String value1, String value2) {
			addCriterion("ip_section between", value1, value2, "ipSection");
			return (Criteria) this;
		}

		public Criteria andIpSectionNotBetween(String value1, String value2) {
			addCriterion("ip_section not between", value1, value2, "ipSection");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table vlan
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vlan
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 29 14:45:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}