package com.whty.cms.tspm.dao;

import com.whty.cms.tspm.pojo.Sequence;
import com.whty.cms.tspm.pojo.SequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int countByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int deleteByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int deleteByPrimaryKey(String seqName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    List<Sequence> selectByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    Sequence selectByPrimaryKey(String seqName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") Sequence record, @Param("example") SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int updateByExample(@Param("record") Sequence record, @Param("example") SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    int updateByPrimaryKey(Sequence record);
}