package com.whty.cms.tspm.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.cms.tspm.pojo.StatisticsToken;
import com.whty.cms.tspm.pojo.StatisticsTokenExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface StatisticsTokenMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int countByExample(StatisticsTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int deleteByExample(StatisticsTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int deleteByPrimaryKey(String statisticsTime);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int insert(StatisticsToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int insertSelective(StatisticsToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	List<StatisticsToken> selectByExample(StatisticsTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	StatisticsToken selectByPrimaryKey(String statisticsTime);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByExampleSelective(@Param("record") StatisticsToken record, @Param("example") StatisticsTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByExample(@Param("record") StatisticsToken record, @Param("example") StatisticsTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByPrimaryKeySelective(StatisticsToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByPrimaryKey(StatisticsToken record);

	PageList<StatisticsToken> selectByExamplePaging(StatisticsTokenExample example, PageBounds pageBounds);

	PageList<StatisticsToken> selectByExamplePagingMonth(StatisticsTokenExample example, PageBounds pageBounds);

	PageList<StatisticsToken> selectByExamplePagingQuarter(StatisticsTokenExample example, PageBounds pageBounds);

	PageList<StatisticsToken> selectByExamplePagingYear(StatisticsTokenExample example, PageBounds pageBounds);

	List<StatisticsToken> selectByExamplePagingMonth(StatisticsTokenExample example);
	
	List<StatisticsToken> selectByExamplePagingQuarter(StatisticsTokenExample example);
	
	List<StatisticsToken> selectByExamplePagingYear(StatisticsTokenExample example);
}