package com.whty.cms.tspm.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.cms.tspm.pojo.TokenOperationHis;
import com.whty.cms.tspm.pojo.TokenOperationHisExample;
import com.whty.cms.tspm.pojo.TokenOperationHisKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TokenOperationHisMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int countByExample(TokenOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int deleteByExample(TokenOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int deleteByPrimaryKey(TokenOperationHisKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int insert(TokenOperationHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int insertSelective(TokenOperationHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	List<TokenOperationHis> selectByExample(TokenOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	TokenOperationHis selectByPrimaryKey(TokenOperationHisKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TokenOperationHis record, @Param("example") TokenOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByExample(@Param("record") TokenOperationHis record, @Param("example") TokenOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByPrimaryKeySelective(TokenOperationHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByPrimaryKey(TokenOperationHis record);

	PageList<TokenOperationHis> selectByExamplePaging(TokenOperationHisExample example, PageBounds pageBounds);
}