package com.whty.cms.tspm.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.cms.tspm.pojo.TokenInfo;
import com.whty.cms.tspm.pojo.TokenInfoExample;
import com.whty.cms.tspm.pojo.TokenInfoKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TokenInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int countByExample(TokenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int deleteByExample(TokenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int deleteByPrimaryKey(TokenInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int insert(TokenInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int insertSelective(TokenInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	List<TokenInfo> selectByExample(TokenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	TokenInfo selectByPrimaryKey(TokenInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TokenInfo record, @Param("example") TokenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByExample(@Param("record") TokenInfo record, @Param("example") TokenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByPrimaryKeySelective(TokenInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByPrimaryKey(TokenInfo record);

	PageList<TokenInfo> selectByExamplePaging(TokenInfoExample example, PageBounds pageBounds);
}