package com.whty.cms.tspm.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.cms.tspm.pojo.TrInfo;
import com.whty.cms.tspm.pojo.TrInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TrInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int countByExample(TrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int deleteByExample(TrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int deleteByPrimaryKey(String pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int insert(TrInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int insertSelective(TrInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	List<TrInfo> selectByExample(TrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	TrInfo selectByPrimaryKey(String pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TrInfo record, @Param("example") TrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int updateByExample(@Param("record") TrInfo record, @Param("example") TrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int updateByPrimaryKeySelective(TrInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	int updateByPrimaryKey(TrInfo record);

	PageList<TrInfo> selectByExamplePaging(TrInfoExample example, PageBounds pageBounds);
}