package com.whty.cms.tspm.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.cms.tspm.pojo.TrOperationHis;
import com.whty.cms.tspm.pojo.TrOperationHisExample;
import com.whty.cms.tspm.pojo.TrOperationHisKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TrOperationHisMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int countByExample(TrOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int deleteByExample(TrOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int deleteByPrimaryKey(TrOperationHisKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int insert(TrOperationHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int insertSelective(TrOperationHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	List<TrOperationHis> selectByExample(TrOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	TrOperationHis selectByPrimaryKey(TrOperationHisKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TrOperationHis record, @Param("example") TrOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByExample(@Param("record") TrOperationHis record, @Param("example") TrOperationHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByPrimaryKeySelective(TrOperationHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_OPERATION_HIS
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	int updateByPrimaryKey(TrOperationHis record);

	PageList<TrOperationHis> selectByExamplePaging(TrOperationHisExample example, PageBounds pageBounds);
}