package com.whty.cms.network.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.cms.network.pojo.ApplyInfo;
import com.whty.cms.network.pojo.ApplyInfoExample;
import com.whty.cms.tspm.pojo.TrInfo;
import com.whty.cms.tspm.pojo.TrInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ApplyInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_info
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	int countByExample(ApplyInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_info
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	int deleteByExample(ApplyInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_info
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	int insert(ApplyInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_info
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	int insertSelective(ApplyInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_info
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	List<ApplyInfo> selectByExample(ApplyInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_info
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ApplyInfo record,
			@Param("example") ApplyInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_info
	 * @mbggenerated  Thu Jul 30 09:21:33 CST 2015
	 */
	int updateByExample(@Param("record") ApplyInfo record,
			@Param("example") ApplyInfoExample example);

	PageList<ApplyInfo> selectByExamplePaging(ApplyInfoExample example, PageBounds pageBounds);
}