package com.whty.cms.network.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.cms.network.pojo.Device;
import com.whty.cms.network.pojo.DeviceExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DeviceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int countByExample(DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int deleteByExample(DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int deleteByPrimaryKey(String deviceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int insert(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int insertSelective(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	List<Device> selectByExample(DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	Device selectByPrimaryKey(String deviceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Device record,
			@Param("example") DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int updateByExample(@Param("record") Device record,
			@Param("example") DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int updateByPrimaryKeySelective(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int updateByPrimaryKey(Device record);

	PageList<Device> selectByExamplePaging(DeviceExample example,
			PageBounds pageBounds);
}