package com.whty.cms.network.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.cms.network.pojo.NetworkAdapter;
import com.whty.cms.network.pojo.NetworkAdapterExample;

public interface NetworkAdapterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int countByExample(NetworkAdapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int deleteByExample(NetworkAdapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int deleteByPrimaryKey(String networkadapterId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int insert(NetworkAdapter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int insertSelective(NetworkAdapter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	List<NetworkAdapter> selectByExample(NetworkAdapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	NetworkAdapter selectByPrimaryKey(String networkadapterId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int updateByExampleSelective(@Param("record") NetworkAdapter record,
			@Param("example") NetworkAdapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int updateByExample(@Param("record") NetworkAdapter record,
			@Param("example") NetworkAdapterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int updateByPrimaryKeySelective(NetworkAdapter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table networkadapter
	 * @mbggenerated  Fri Aug 21 16:44:04 CST 2015
	 */
	int updateByPrimaryKey(NetworkAdapter record);
	
	PageList<NetworkAdapter> selectByExamplePaging(NetworkAdapterExample example,
			PageBounds pageBounds);
}