package com.whty.cms.network.dao;

import com.whty.cms.network.pojo.Switch;
import com.whty.cms.network.pojo.SwitchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SwitchMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int countByExample(SwitchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int deleteByExample(SwitchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int deleteByPrimaryKey(Integer switchId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int insert(Switch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int insertSelective(Switch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	List<Switch> selectByExample(SwitchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	Switch selectByPrimaryKey(Integer switchId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Switch record,
			@Param("example") SwitchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int updateByExample(@Param("record") Switch record,
			@Param("example") SwitchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int updateByPrimaryKeySelective(Switch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switch
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int updateByPrimaryKey(Switch record);
}