package com.whty.cms.network.dao;

import com.whty.cms.network.pojo.SwitchPort;
import com.whty.cms.network.pojo.SwitchPortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SwitchPortMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int countByExample(SwitchPortExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int deleteByExample(SwitchPortExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int deleteByPrimaryKey(Integer switchPortId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int insert(SwitchPort record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int insertSelective(SwitchPort record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	List<SwitchPort> selectByExample(SwitchPortExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	SwitchPort selectByPrimaryKey(Integer switchPortId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int updateByExampleSelective(@Param("record") SwitchPort record,
			@Param("example") SwitchPortExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int updateByExample(@Param("record") SwitchPort record,
			@Param("example") SwitchPortExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int updateByPrimaryKeySelective(SwitchPort record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table switchport
	 * @mbggenerated  Thu Aug 20 13:37:45 CST 2015
	 */
	int updateByPrimaryKey(SwitchPort record);
}