package com.whty.cms.tspm.pojo;

public class Sequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCE.SEQ_NAME
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    private String seqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCE.CURRENT_VAL
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    private Integer currentVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCE.INCREMENT_VAL
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    private Integer incrementVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCE.SEQ_NAME
     *
     * @return the value of SEQUENCE.SEQ_NAME
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCE.SEQ_NAME
     *
     * @param seqName the value for SEQUENCE.SEQ_NAME
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName == null ? null : seqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCE.CURRENT_VAL
     *
     * @return the value of SEQUENCE.CURRENT_VAL
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    public Integer getCurrentVal() {
        return currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCE.CURRENT_VAL
     *
     * @param currentVal the value for SEQUENCE.CURRENT_VAL
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    public void setCurrentVal(Integer currentVal) {
        this.currentVal = currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCE.INCREMENT_VAL
     *
     * @return the value of SEQUENCE.INCREMENT_VAL
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    public Integer getIncrementVal() {
        return incrementVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCE.INCREMENT_VAL
     *
     * @param incrementVal the value for SEQUENCE.INCREMENT_VAL
     *
     * @mbggenerated Mon Jun 08 10:17:37 CST 2015
     */
    public void setIncrementVal(Integer incrementVal) {
        this.incrementVal = incrementVal;
    }
}