package com.whty.cms.tspm.pojo;

import java.util.ArrayList;
import java.util.List;

public class StatisticsTokenExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public StatisticsTokenExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStatisticsTimeIsNull() {
			addCriterion("STATISTICS_TIME is null");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeIsNotNull() {
			addCriterion("STATISTICS_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeEqualTo(String value) {
			addCriterion("STATISTICS_TIME =", value, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeNotEqualTo(String value) {
			addCriterion("STATISTICS_TIME <>", value, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeGreaterThan(String value) {
			addCriterion("STATISTICS_TIME >", value, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeGreaterThanOrEqualTo(String value) {
			addCriterion("STATISTICS_TIME >=", value, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeLessThan(String value) {
			addCriterion("STATISTICS_TIME <", value, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeLessThanOrEqualTo(String value) {
			addCriterion("STATISTICS_TIME <=", value, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeLike(String value) {
			addCriterion("STATISTICS_TIME like", value, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeNotLike(String value) {
			addCriterion("STATISTICS_TIME not like", value, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeIn(List<String> values) {
			addCriterion("STATISTICS_TIME in", values, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeNotIn(List<String> values) {
			addCriterion("STATISTICS_TIME not in", values, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeBetween(String value1, String value2) {
			addCriterion("STATISTICS_TIME between", value1, value2, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andStatisticsTimeNotBetween(String value1, String value2) {
			addCriterion("STATISTICS_TIME not between", value1, value2, "statisticsTime");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumIsNull() {
			addCriterion("TOKEN_CREATE_SUM_NUM is null");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumIsNotNull() {
			addCriterion("TOKEN_CREATE_SUM_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumEqualTo(Integer value) {
			addCriterion("TOKEN_CREATE_SUM_NUM =", value, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumNotEqualTo(Integer value) {
			addCriterion("TOKEN_CREATE_SUM_NUM <>", value, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumGreaterThan(Integer value) {
			addCriterion("TOKEN_CREATE_SUM_NUM >", value, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("TOKEN_CREATE_SUM_NUM >=", value, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumLessThan(Integer value) {
			addCriterion("TOKEN_CREATE_SUM_NUM <", value, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumLessThanOrEqualTo(Integer value) {
			addCriterion("TOKEN_CREATE_SUM_NUM <=", value, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumIn(List<Integer> values) {
			addCriterion("TOKEN_CREATE_SUM_NUM in", values, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumNotIn(List<Integer> values) {
			addCriterion("TOKEN_CREATE_SUM_NUM not in", values, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumBetween(Integer value1, Integer value2) {
			addCriterion("TOKEN_CREATE_SUM_NUM between", value1, value2, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenCreateSumNumNotBetween(Integer value1, Integer value2) {
			addCriterion("TOKEN_CREATE_SUM_NUM not between", value1, value2, "tokenCreateSumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumIsNull() {
			addCriterion("TOKEN_DESTORY_SUM_NUM is null");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumIsNotNull() {
			addCriterion("TOKEN_DESTORY_SUM_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumEqualTo(Integer value) {
			addCriterion("TOKEN_DESTORY_SUM_NUM =", value, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumNotEqualTo(Integer value) {
			addCriterion("TOKEN_DESTORY_SUM_NUM <>", value, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumGreaterThan(Integer value) {
			addCriterion("TOKEN_DESTORY_SUM_NUM >", value, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("TOKEN_DESTORY_SUM_NUM >=", value, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumLessThan(Integer value) {
			addCriterion("TOKEN_DESTORY_SUM_NUM <", value, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumLessThanOrEqualTo(Integer value) {
			addCriterion("TOKEN_DESTORY_SUM_NUM <=", value, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumIn(List<Integer> values) {
			addCriterion("TOKEN_DESTORY_SUM_NUM in", values, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumNotIn(List<Integer> values) {
			addCriterion("TOKEN_DESTORY_SUM_NUM not in", values, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumBetween(Integer value1, Integer value2) {
			addCriterion("TOKEN_DESTORY_SUM_NUM between", value1, value2, "tokenDestorySumNum");
			return (Criteria) this;
		}

		public Criteria andTokenDestorySumNumNotBetween(Integer value1, Integer value2) {
			addCriterion("TOKEN_DESTORY_SUM_NUM not between", value1, value2, "tokenDestorySumNum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table STATISTICS_TOKEN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STATISTICS_TOKEN
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 04 09:32:20 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}