package com.whty.cms.tspm.pojo;

public class StatisticsTr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STATISTICS_TR.STATISTICS_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String statisticsTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STATISTICS_TR.TR_CREATE_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private Integer trCreateSumNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STATISTICS_TR.TR_DESTORY_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private Integer trDestorySumNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STATISTICS_TR.STATISTICS_TIME
	 * @return  the value of STATISTICS_TR.STATISTICS_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getStatisticsTime() {
		return statisticsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STATISTICS_TR.STATISTICS_TIME
	 * @param statisticsTime  the value for STATISTICS_TR.STATISTICS_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setStatisticsTime(String statisticsTime) {
		this.statisticsTime = statisticsTime == null ? null : statisticsTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STATISTICS_TR.TR_CREATE_SUM_NUM
	 * @return  the value of STATISTICS_TR.TR_CREATE_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Integer getTrCreateSumNum() {
		return trCreateSumNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STATISTICS_TR.TR_CREATE_SUM_NUM
	 * @param trCreateSumNum  the value for STATISTICS_TR.TR_CREATE_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTrCreateSumNum(Integer trCreateSumNum) {
		this.trCreateSumNum = trCreateSumNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STATISTICS_TR.TR_DESTORY_SUM_NUM
	 * @return  the value of STATISTICS_TR.TR_DESTORY_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Integer getTrDestorySumNum() {
		return trDestorySumNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STATISTICS_TR.TR_DESTORY_SUM_NUM
	 * @param trDestorySumNum  the value for STATISTICS_TR.TR_DESTORY_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTrDestorySumNum(Integer trDestorySumNum) {
		this.trDestorySumNum = trDestorySumNum;
	}
}