package com.whty.cms.tspm.pojo;

public class StatisticsToken {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STATISTICS_TOKEN.STATISTICS_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String statisticsTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STATISTICS_TOKEN.TOKEN_CREATE_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private Integer tokenCreateSumNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STATISTICS_TOKEN.TOKEN_DESTORY_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private Integer tokenDestorySumNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STATISTICS_TOKEN.STATISTICS_TIME
	 * @return  the value of STATISTICS_TOKEN.STATISTICS_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getStatisticsTime() {
		return statisticsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STATISTICS_TOKEN.STATISTICS_TIME
	 * @param statisticsTime  the value for STATISTICS_TOKEN.STATISTICS_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setStatisticsTime(String statisticsTime) {
		this.statisticsTime = statisticsTime == null ? null : statisticsTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STATISTICS_TOKEN.TOKEN_CREATE_SUM_NUM
	 * @return  the value of STATISTICS_TOKEN.TOKEN_CREATE_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Integer getTokenCreateSumNum() {
		return tokenCreateSumNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STATISTICS_TOKEN.TOKEN_CREATE_SUM_NUM
	 * @param tokenCreateSumNum  the value for STATISTICS_TOKEN.TOKEN_CREATE_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTokenCreateSumNum(Integer tokenCreateSumNum) {
		this.tokenCreateSumNum = tokenCreateSumNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STATISTICS_TOKEN.TOKEN_DESTORY_SUM_NUM
	 * @return  the value of STATISTICS_TOKEN.TOKEN_DESTORY_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Integer getTokenDestorySumNum() {
		return tokenDestorySumNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STATISTICS_TOKEN.TOKEN_DESTORY_SUM_NUM
	 * @param tokenDestorySumNum  the value for STATISTICS_TOKEN.TOKEN_DESTORY_SUM_NUM
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTokenDestorySumNum(Integer tokenDestorySumNum) {
		this.tokenDestorySumNum = tokenDestorySumNum;
	}
}