package com.whty.cms.tspm.pojo;

public class TokenInfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.TOKEN_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String tokenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.TR_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String trId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.TOKEN_ID
	 * @return  the value of TOKEN_INFO.TOKEN_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getTokenId() {
		return tokenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.TOKEN_ID
	 * @param tokenId  the value for TOKEN_INFO.TOKEN_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTokenId(String tokenId) {
		this.tokenId = tokenId == null ? null : tokenId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.TR_ID
	 * @return  the value of TOKEN_INFO.TR_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.TR_ID
	 * @param trId  the value for TOKEN_INFO.TR_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTrId(String trId) {
		this.trId = trId == null ? null : trId.trim();
	}
}