package com.whty.cms.tspm.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TokenInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public TokenInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTokenIdIsNull() {
			addCriterion("TOKEN_ID is null");
			return (Criteria) this;
		}

		public Criteria andTokenIdIsNotNull() {
			addCriterion("TOKEN_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTokenIdEqualTo(String value) {
			addCriterion("TOKEN_ID =", value, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdNotEqualTo(String value) {
			addCriterion("TOKEN_ID <>", value, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdGreaterThan(String value) {
			addCriterion("TOKEN_ID >", value, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdGreaterThanOrEqualTo(String value) {
			addCriterion("TOKEN_ID >=", value, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdLessThan(String value) {
			addCriterion("TOKEN_ID <", value, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdLessThanOrEqualTo(String value) {
			addCriterion("TOKEN_ID <=", value, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdLike(String value) {
			addCriterion("TOKEN_ID like", value, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdNotLike(String value) {
			addCriterion("TOKEN_ID not like", value, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdIn(List<String> values) {
			addCriterion("TOKEN_ID in", values, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdNotIn(List<String> values) {
			addCriterion("TOKEN_ID not in", values, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdBetween(String value1, String value2) {
			addCriterion("TOKEN_ID between", value1, value2, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTokenIdNotBetween(String value1, String value2) {
			addCriterion("TOKEN_ID not between", value1, value2, "tokenId");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNull() {
			addCriterion("TR_ID is null");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNotNull() {
			addCriterion("TR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTrIdEqualTo(String value) {
			addCriterion("TR_ID =", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotEqualTo(String value) {
			addCriterion("TR_ID <>", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThan(String value) {
			addCriterion("TR_ID >", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThanOrEqualTo(String value) {
			addCriterion("TR_ID >=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThan(String value) {
			addCriterion("TR_ID <", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThanOrEqualTo(String value) {
			addCriterion("TR_ID <=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLike(String value) {
			addCriterion("binary TR_ID like", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotLike(String value) {
			addCriterion("TR_ID not like", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdIn(List<String> values) {
			addCriterion("TR_ID in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotIn(List<String> values) {
			addCriterion("TR_ID not in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdBetween(String value1, String value2) {
			addCriterion("TR_ID between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotBetween(String value1, String value2) {
			addCriterion("TR_ID not between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andBinIsNull() {
			addCriterion("BIN is null");
			return (Criteria) this;
		}

		public Criteria andBinIsNotNull() {
			addCriterion("BIN is not null");
			return (Criteria) this;
		}

		public Criteria andBinEqualTo(String value) {
			addCriterion("BIN =", value, "bin");
			return (Criteria) this;
		}

		public Criteria andBinNotEqualTo(String value) {
			addCriterion("BIN <>", value, "bin");
			return (Criteria) this;
		}

		public Criteria andBinGreaterThan(String value) {
			addCriterion("BIN >", value, "bin");
			return (Criteria) this;
		}

		public Criteria andBinGreaterThanOrEqualTo(String value) {
			addCriterion("BIN >=", value, "bin");
			return (Criteria) this;
		}

		public Criteria andBinLessThan(String value) {
			addCriterion("BIN <", value, "bin");
			return (Criteria) this;
		}

		public Criteria andBinLessThanOrEqualTo(String value) {
			addCriterion("BIN <=", value, "bin");
			return (Criteria) this;
		}

		public Criteria andBinLike(String value) {
			addCriterion("binary BIN like", value, "bin");
			return (Criteria) this;
		}

		public Criteria andBinNotLike(String value) {
			addCriterion("BIN not like", value, "bin");
			return (Criteria) this;
		}

		public Criteria andBinIn(List<String> values) {
			addCriterion("BIN in", values, "bin");
			return (Criteria) this;
		}

		public Criteria andBinNotIn(List<String> values) {
			addCriterion("BIN not in", values, "bin");
			return (Criteria) this;
		}

		public Criteria andBinBetween(String value1, String value2) {
			addCriterion("BIN between", value1, value2, "bin");
			return (Criteria) this;
		}

		public Criteria andBinNotBetween(String value1, String value2) {
			addCriterion("BIN not between", value1, value2, "bin");
			return (Criteria) this;
		}

		public Criteria andPanIsNull() {
			addCriterion("PAN is null");
			return (Criteria) this;
		}

		public Criteria andPanIsNotNull() {
			addCriterion("PAN is not null");
			return (Criteria) this;
		}

		public Criteria andPanEqualTo(String value) {
			addCriterion("PAN =", value, "pan");
			return (Criteria) this;
		}

		public Criteria andPanNotEqualTo(String value) {
			addCriterion("PAN <>", value, "pan");
			return (Criteria) this;
		}

		public Criteria andPanGreaterThan(String value) {
			addCriterion("PAN >", value, "pan");
			return (Criteria) this;
		}

		public Criteria andPanGreaterThanOrEqualTo(String value) {
			addCriterion("PAN >=", value, "pan");
			return (Criteria) this;
		}

		public Criteria andPanLessThan(String value) {
			addCriterion("PAN <", value, "pan");
			return (Criteria) this;
		}

		public Criteria andPanLessThanOrEqualTo(String value) {
			addCriterion("PAN <=", value, "pan");
			return (Criteria) this;
		}

		public Criteria andPanLike(String value) {
			addCriterion("binary PAN like", value, "pan");
			return (Criteria) this;
		}

		public Criteria andPanNotLike(String value) {
			addCriterion("PAN not like", value, "pan");
			return (Criteria) this;
		}

		public Criteria andPanIn(List<String> values) {
			addCriterion("PAN in", values, "pan");
			return (Criteria) this;
		}

		public Criteria andPanNotIn(List<String> values) {
			addCriterion("PAN not in", values, "pan");
			return (Criteria) this;
		}

		public Criteria andPanBetween(String value1, String value2) {
			addCriterion("PAN between", value1, value2, "pan");
			return (Criteria) this;
		}

		public Criteria andPanNotBetween(String value1, String value2) {
			addCriterion("PAN not between", value1, value2, "pan");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeIsNull() {
			addCriterion("INVALID_TIME is null");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeIsNotNull() {
			addCriterion("INVALID_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeEqualTo(Date value) {
			addCriterion("INVALID_TIME =", value, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeNotEqualTo(Date value) {
			addCriterion("INVALID_TIME <>", value, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeGreaterThan(Date value) {
			addCriterion("INVALID_TIME >", value, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("INVALID_TIME >=", value, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeLessThan(Date value) {
			addCriterion("INVALID_TIME <", value, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeLessThanOrEqualTo(Date value) {
			addCriterion("INVALID_TIME <=", value, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeIn(List<Date> values) {
			addCriterion("INVALID_TIME in", values, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeNotIn(List<Date> values) {
			addCriterion("INVALID_TIME not in", values, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeBetween(Date value1, Date value2) {
			addCriterion("INVALID_TIME between", value1, value2, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andInvalidTimeNotBetween(Date value1, Date value2) {
			addCriterion("INVALID_TIME not between", value1, value2, "invalidTime");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesIsNull() {
			addCriterion("TRADE_SUM_TIMES is null");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesIsNotNull() {
			addCriterion("TRADE_SUM_TIMES is not null");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesEqualTo(Integer value) {
			addCriterion("TRADE_SUM_TIMES =", value, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesNotEqualTo(Integer value) {
			addCriterion("TRADE_SUM_TIMES <>", value, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesGreaterThan(Integer value) {
			addCriterion("TRADE_SUM_TIMES >", value, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("TRADE_SUM_TIMES >=", value, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesLessThan(Integer value) {
			addCriterion("TRADE_SUM_TIMES <", value, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesLessThanOrEqualTo(Integer value) {
			addCriterion("TRADE_SUM_TIMES <=", value, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesIn(List<Integer> values) {
			addCriterion("TRADE_SUM_TIMES in", values, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesNotIn(List<Integer> values) {
			addCriterion("TRADE_SUM_TIMES not in", values, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesBetween(Integer value1, Integer value2) {
			addCriterion("TRADE_SUM_TIMES between", value1, value2, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumTimesNotBetween(Integer value1, Integer value2) {
			addCriterion("TRADE_SUM_TIMES not between", value1, value2, "tradeSumTimes");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyIsNull() {
			addCriterion("TRADE_SUM_MONEY is null");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyIsNotNull() {
			addCriterion("TRADE_SUM_MONEY is not null");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyEqualTo(BigDecimal value) {
			addCriterion("TRADE_SUM_MONEY =", value, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyNotEqualTo(BigDecimal value) {
			addCriterion("TRADE_SUM_MONEY <>", value, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyGreaterThan(BigDecimal value) {
			addCriterion("TRADE_SUM_MONEY >", value, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("TRADE_SUM_MONEY >=", value, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyLessThan(BigDecimal value) {
			addCriterion("TRADE_SUM_MONEY <", value, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("TRADE_SUM_MONEY <=", value, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyIn(List<BigDecimal> values) {
			addCriterion("TRADE_SUM_MONEY in", values, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyNotIn(List<BigDecimal> values) {
			addCriterion("TRADE_SUM_MONEY not in", values, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TRADE_SUM_MONEY between", value1, value2, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTradeSumMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TRADE_SUM_MONEY not between", value1, value2, "tradeSumMoney");
			return (Criteria) this;
		}

		public Criteria andTokenLevelIsNull() {
			addCriterion("TOKEN_LEVEL is null");
			return (Criteria) this;
		}

		public Criteria andTokenLevelIsNotNull() {
			addCriterion("TOKEN_LEVEL is not null");
			return (Criteria) this;
		}

		public Criteria andTokenLevelEqualTo(String value) {
			addCriterion("TOKEN_LEVEL =", value, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelNotEqualTo(String value) {
			addCriterion("TOKEN_LEVEL <>", value, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelGreaterThan(String value) {
			addCriterion("TOKEN_LEVEL >", value, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelGreaterThanOrEqualTo(String value) {
			addCriterion("TOKEN_LEVEL >=", value, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelLessThan(String value) {
			addCriterion("TOKEN_LEVEL <", value, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelLessThanOrEqualTo(String value) {
			addCriterion("TOKEN_LEVEL <=", value, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelLike(String value) {
			addCriterion("TOKEN_LEVEL like", value, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelNotLike(String value) {
			addCriterion("TOKEN_LEVEL not like", value, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelIn(List<String> values) {
			addCriterion("TOKEN_LEVEL in", values, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelNotIn(List<String> values) {
			addCriterion("TOKEN_LEVEL not in", values, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelBetween(String value1, String value2) {
			addCriterion("TOKEN_LEVEL between", value1, value2, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenLevelNotBetween(String value1, String value2) {
			addCriterion("TOKEN_LEVEL not between", value1, value2, "tokenLevel");
			return (Criteria) this;
		}

		public Criteria andTokenFlagIsNull() {
			addCriterion("TOKEN_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andTokenFlagIsNotNull() {
			addCriterion("TOKEN_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andTokenFlagEqualTo(String value) {
			addCriterion("TOKEN_FLAG =", value, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagNotEqualTo(String value) {
			addCriterion("TOKEN_FLAG <>", value, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagGreaterThan(String value) {
			addCriterion("TOKEN_FLAG >", value, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagGreaterThanOrEqualTo(String value) {
			addCriterion("TOKEN_FLAG >=", value, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagLessThan(String value) {
			addCriterion("TOKEN_FLAG <", value, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagLessThanOrEqualTo(String value) {
			addCriterion("TOKEN_FLAG <=", value, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagLike(String value) {
			addCriterion("TOKEN_FLAG like", value, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagNotLike(String value) {
			addCriterion("TOKEN_FLAG not like", value, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagIn(List<String> values) {
			addCriterion("TOKEN_FLAG in", values, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagNotIn(List<String> values) {
			addCriterion("TOKEN_FLAG not in", values, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagBetween(String value1, String value2) {
			addCriterion("TOKEN_FLAG between", value1, value2, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andTokenFlagNotBetween(String value1, String value2) {
			addCriterion("TOKEN_FLAG not between", value1, value2, "tokenFlag");
			return (Criteria) this;
		}

		public Criteria andUserAccountIsNull() {
			addCriterion("USER_ACCOUNT is null");
			return (Criteria) this;
		}

		public Criteria andUserAccountIsNotNull() {
			addCriterion("USER_ACCOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andUserAccountEqualTo(String value) {
			addCriterion("USER_ACCOUNT =", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotEqualTo(String value) {
			addCriterion("USER_ACCOUNT <>", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountGreaterThan(String value) {
			addCriterion("USER_ACCOUNT >", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ACCOUNT >=", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLessThan(String value) {
			addCriterion("USER_ACCOUNT <", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLessThanOrEqualTo(String value) {
			addCriterion("USER_ACCOUNT <=", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLike(String value) {
			addCriterion("USER_ACCOUNT like", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotLike(String value) {
			addCriterion("USER_ACCOUNT not like", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountIn(List<String> values) {
			addCriterion("USER_ACCOUNT in", values, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotIn(List<String> values) {
			addCriterion("USER_ACCOUNT not in", values, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountBetween(String value1, String value2) {
			addCriterion("USER_ACCOUNT between", value1, value2, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotBetween(String value1, String value2) {
			addCriterion("USER_ACCOUNT not between", value1, value2, "userAccount");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TOKEN_INFO
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TOKEN_INFO
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 04 09:32:20 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}