package com.whty.cms.tspm.pojo;

public class TokenOperationHis extends TokenOperationHisKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_OPERATION_HIS.TR_OPERATION_TYPE
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String trOperationType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_OPERATION_HIS.TR_OPERATION_TYPE
	 * @return  the value of TOKEN_OPERATION_HIS.TR_OPERATION_TYPE
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getTrOperationType() {
		return trOperationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_OPERATION_HIS.TR_OPERATION_TYPE
	 * @param trOperationType  the value for TOKEN_OPERATION_HIS.TR_OPERATION_TYPE
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTrOperationType(String trOperationType) {
		this.trOperationType = trOperationType == null ? null : trOperationType.trim();
	}
}