package com.whty.cms.tspm.pojo;

import java.util.Date;

public class TokenOperationHisKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_OPERATION_HIS.OPERATION_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private Date operationTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_OPERATION_HIS.TOKEN_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String tokenId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_OPERATION_HIS.OPERATION_TIME
	 * @return  the value of TOKEN_OPERATION_HIS.OPERATION_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Date getOperationTime() {
		return operationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_OPERATION_HIS.OPERATION_TIME
	 * @param operationTime  the value for TOKEN_OPERATION_HIS.OPERATION_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_OPERATION_HIS.TOKEN_ID
	 * @return  the value of TOKEN_OPERATION_HIS.TOKEN_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getTokenId() {
		return tokenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_OPERATION_HIS.TOKEN_ID
	 * @param tokenId  the value for TOKEN_OPERATION_HIS.TOKEN_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTokenId(String tokenId) {
		this.tokenId = tokenId == null ? null : tokenId.trim();
	}
}