package com.whty.cms.tspm.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TokenInfo extends TokenInfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.BIN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String bin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.PAN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String pan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.INVALID_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private Date invalidTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.TRADE_SUM_TIMES
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private Integer tradeSumTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.TRADE_SUM_MONEY
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private BigDecimal tradeSumMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.TOKEN_LEVEL
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String tokenLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.TOKEN_FLAG
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String tokenFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN_INFO.USER_ACCOUNT
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String userAccount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.BIN
	 * @return  the value of TOKEN_INFO.BIN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getBin() {
		return bin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.BIN
	 * @param bin  the value for TOKEN_INFO.BIN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setBin(String bin) {
		this.bin = bin == null ? null : bin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.PAN
	 * @return  the value of TOKEN_INFO.PAN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getPan() {
		return pan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.PAN
	 * @param pan  the value for TOKEN_INFO.PAN
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setPan(String pan) {
		this.pan = pan == null ? null : pan.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.INVALID_TIME
	 * @return  the value of TOKEN_INFO.INVALID_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Date getInvalidTime() {
		return invalidTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.INVALID_TIME
	 * @param invalidTime  the value for TOKEN_INFO.INVALID_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setInvalidTime(Date invalidTime) {
		this.invalidTime = invalidTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.TRADE_SUM_TIMES
	 * @return  the value of TOKEN_INFO.TRADE_SUM_TIMES
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Integer getTradeSumTimes() {
		return tradeSumTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.TRADE_SUM_TIMES
	 * @param tradeSumTimes  the value for TOKEN_INFO.TRADE_SUM_TIMES
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTradeSumTimes(Integer tradeSumTimes) {
		this.tradeSumTimes = tradeSumTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.TRADE_SUM_MONEY
	 * @return  the value of TOKEN_INFO.TRADE_SUM_MONEY
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public BigDecimal getTradeSumMoney() {
		return tradeSumMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.TRADE_SUM_MONEY
	 * @param tradeSumMoney  the value for TOKEN_INFO.TRADE_SUM_MONEY
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTradeSumMoney(BigDecimal tradeSumMoney) {
		this.tradeSumMoney = tradeSumMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.TOKEN_LEVEL
	 * @return  the value of TOKEN_INFO.TOKEN_LEVEL
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getTokenLevel() {
		return tokenLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.TOKEN_LEVEL
	 * @param tokenLevel  the value for TOKEN_INFO.TOKEN_LEVEL
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTokenLevel(String tokenLevel) {
		this.tokenLevel = tokenLevel == null ? null : tokenLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.TOKEN_FLAG
	 * @return  the value of TOKEN_INFO.TOKEN_FLAG
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getTokenFlag() {
		return tokenFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.TOKEN_FLAG
	 * @param tokenFlag  the value for TOKEN_INFO.TOKEN_FLAG
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTokenFlag(String tokenFlag) {
		this.tokenFlag = tokenFlag == null ? null : tokenFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN_INFO.USER_ACCOUNT
	 * @return  the value of TOKEN_INFO.USER_ACCOUNT
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getUserAccount() {
		return userAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN_INFO.USER_ACCOUNT
	 * @param userAccount  the value for TOKEN_INFO.USER_ACCOUNT
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount == null ? null : userAccount.trim();
	}
}