package com.whty.cms.tspm.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TrInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public TrInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPkIsNull() {
			addCriterion("PK is null");
			return (Criteria) this;
		}

		public Criteria andPkIsNotNull() {
			addCriterion("PK is not null");
			return (Criteria) this;
		}

		public Criteria andPkEqualTo(String value) {
			addCriterion("PK =", value, "pk");
			return (Criteria) this;
		}

		public Criteria andPkNotEqualTo(String value) {
			addCriterion("PK <>", value, "pk");
			return (Criteria) this;
		}

		public Criteria andPkGreaterThan(String value) {
			addCriterion("PK >", value, "pk");
			return (Criteria) this;
		}

		public Criteria andPkGreaterThanOrEqualTo(String value) {
			addCriterion("PK >=", value, "pk");
			return (Criteria) this;
		}

		public Criteria andPkLessThan(String value) {
			addCriterion("PK <", value, "pk");
			return (Criteria) this;
		}

		public Criteria andPkLessThanOrEqualTo(String value) {
			addCriterion("PK <=", value, "pk");
			return (Criteria) this;
		}

		public Criteria andPkLike(String value) {
			addCriterion("PK like", value, "pk");
			return (Criteria) this;
		}

		public Criteria andPkNotLike(String value) {
			addCriterion("PK not like", value, "pk");
			return (Criteria) this;
		}

		public Criteria andPkIn(List<String> values) {
			addCriterion("PK in", values, "pk");
			return (Criteria) this;
		}

		public Criteria andPkNotIn(List<String> values) {
			addCriterion("PK not in", values, "pk");
			return (Criteria) this;
		}

		public Criteria andPkBetween(String value1, String value2) {
			addCriterion("PK between", value1, value2, "pk");
			return (Criteria) this;
		}

		public Criteria andPkNotBetween(String value1, String value2) {
			addCriterion("PK not between", value1, value2, "pk");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNull() {
			addCriterion("TR_ID is null");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNotNull() {
			addCriterion("TR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTrIdEqualTo(String value) {
			addCriterion("TR_ID =", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotEqualTo(String value) {
			addCriterion("TR_ID <>", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThan(String value) {
			addCriterion("TR_ID >", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThanOrEqualTo(String value) {
			addCriterion("TR_ID >=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThan(String value) {
			addCriterion("TR_ID <", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThanOrEqualTo(String value) {
			addCriterion("TR_ID <=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLike(String value) {
			addCriterion("TR_ID like", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotLike(String value) {
			addCriterion("TR_ID not like", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdIn(List<String> values) {
			addCriterion("TR_ID in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotIn(List<String> values) {
			addCriterion("TR_ID not in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdBetween(String value1, String value2) {
			addCriterion("TR_ID between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotBetween(String value1, String value2) {
			addCriterion("TR_ID not between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andTrVersionIsNull() {
			addCriterion("TR_VERSION is null");
			return (Criteria) this;
		}

		public Criteria andTrVersionIsNotNull() {
			addCriterion("TR_VERSION is not null");
			return (Criteria) this;
		}

		public Criteria andTrVersionEqualTo(String value) {
			addCriterion("TR_VERSION =", value, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionNotEqualTo(String value) {
			addCriterion("TR_VERSION <>", value, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionGreaterThan(String value) {
			addCriterion("TR_VERSION >", value, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionGreaterThanOrEqualTo(String value) {
			addCriterion("TR_VERSION >=", value, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionLessThan(String value) {
			addCriterion("TR_VERSION <", value, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionLessThanOrEqualTo(String value) {
			addCriterion("TR_VERSION <=", value, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionLike(String value) {
			addCriterion("TR_VERSION like", value, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionNotLike(String value) {
			addCriterion("TR_VERSION not like", value, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionIn(List<String> values) {
			addCriterion("TR_VERSION in", values, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionNotIn(List<String> values) {
			addCriterion("TR_VERSION not in", values, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionBetween(String value1, String value2) {
			addCriterion("TR_VERSION between", value1, value2, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrVersionNotBetween(String value1, String value2) {
			addCriterion("TR_VERSION not between", value1, value2, "trVersion");
			return (Criteria) this;
		}

		public Criteria andTrLevelIsNull() {
			addCriterion("TR_LEVEL is null");
			return (Criteria) this;
		}

		public Criteria andTrLevelIsNotNull() {
			addCriterion("TR_LEVEL is not null");
			return (Criteria) this;
		}

		public Criteria andTrLevelEqualTo(String value) {
			addCriterion("TR_LEVEL =", value, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelNotEqualTo(String value) {
			addCriterion("TR_LEVEL <>", value, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelGreaterThan(String value) {
			addCriterion("TR_LEVEL >", value, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelGreaterThanOrEqualTo(String value) {
			addCriterion("TR_LEVEL >=", value, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelLessThan(String value) {
			addCriterion("TR_LEVEL <", value, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelLessThanOrEqualTo(String value) {
			addCriterion("TR_LEVEL <=", value, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelLike(String value) {
			addCriterion("TR_LEVEL like", value, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelNotLike(String value) {
			addCriterion("TR_LEVEL not like", value, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelIn(List<String> values) {
			addCriterion("TR_LEVEL in", values, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelNotIn(List<String> values) {
			addCriterion("TR_LEVEL not in", values, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelBetween(String value1, String value2) {
			addCriterion("TR_LEVEL between", value1, value2, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrLevelNotBetween(String value1, String value2) {
			addCriterion("TR_LEVEL not between", value1, value2, "trLevel");
			return (Criteria) this;
		}

		public Criteria andTrAreaIsNull() {
			addCriterion("TR_AREA is null");
			return (Criteria) this;
		}

		public Criteria andTrAreaIsNotNull() {
			addCriterion("TR_AREA is not null");
			return (Criteria) this;
		}

		public Criteria andTrAreaEqualTo(String value) {
			addCriterion("TR_AREA =", value, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaNotEqualTo(String value) {
			addCriterion("TR_AREA <>", value, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaGreaterThan(String value) {
			addCriterion("TR_AREA >", value, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaGreaterThanOrEqualTo(String value) {
			addCriterion("TR_AREA >=", value, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaLessThan(String value) {
			addCriterion("TR_AREA <", value, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaLessThanOrEqualTo(String value) {
			addCriterion("TR_AREA <=", value, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaLike(String value) {
			addCriterion("TR_AREA like", value, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaNotLike(String value) {
			addCriterion("TR_AREA not like", value, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaIn(List<String> values) {
			addCriterion("TR_AREA in", values, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaNotIn(List<String> values) {
			addCriterion("TR_AREA not in", values, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaBetween(String value1, String value2) {
			addCriterion("TR_AREA between", value1, value2, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrAreaNotBetween(String value1, String value2) {
			addCriterion("TR_AREA not between", value1, value2, "trArea");
			return (Criteria) this;
		}

		public Criteria andTrTimeIsNull() {
			addCriterion("TR_TIME is null");
			return (Criteria) this;
		}

		public Criteria andTrTimeIsNotNull() {
			addCriterion("TR_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andTrTimeEqualTo(Date value) {
			addCriterion("TR_TIME =", value, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeNotEqualTo(Date value) {
			addCriterion("TR_TIME <>", value, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeGreaterThan(Date value) {
			addCriterion("TR_TIME >", value, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("TR_TIME >=", value, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeLessThan(Date value) {
			addCriterion("TR_TIME <", value, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeLessThanOrEqualTo(Date value) {
			addCriterion("TR_TIME <=", value, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeIn(List<Date> values) {
			addCriterion("TR_TIME in", values, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeNotIn(List<Date> values) {
			addCriterion("TR_TIME not in", values, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeBetween(Date value1, Date value2) {
			addCriterion("TR_TIME between", value1, value2, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrTimeNotBetween(Date value1, Date value2) {
			addCriterion("TR_TIME not between", value1, value2, "trTime");
			return (Criteria) this;
		}

		public Criteria andTrFlagIsNull() {
			addCriterion("TR_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andTrFlagIsNotNull() {
			addCriterion("TR_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andTrFlagEqualTo(String value) {
			addCriterion("TR_FLAG =", value, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagNotEqualTo(String value) {
			addCriterion("TR_FLAG <>", value, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagGreaterThan(String value) {
			addCriterion("TR_FLAG >", value, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagGreaterThanOrEqualTo(String value) {
			addCriterion("TR_FLAG >=", value, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagLessThan(String value) {
			addCriterion("TR_FLAG <", value, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagLessThanOrEqualTo(String value) {
			addCriterion("TR_FLAG <=", value, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagLike(String value) {
			addCriterion("TR_FLAG like", value, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagNotLike(String value) {
			addCriterion("TR_FLAG not like", value, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagIn(List<String> values) {
			addCriterion("TR_FLAG in", values, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagNotIn(List<String> values) {
			addCriterion("TR_FLAG not in", values, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagBetween(String value1, String value2) {
			addCriterion("TR_FLAG between", value1, value2, "trFlag");
			return (Criteria) this;
		}

		public Criteria andTrFlagNotBetween(String value1, String value2) {
			addCriterion("TR_FLAG not between", value1, value2, "trFlag");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("REMARK in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("REMARK not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TR_INFO
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TR_INFO
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 04 09:33:49 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}