package com.whty.cms.tspm.pojo;

import java.util.Date;

public class TrInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_INFO.PK
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	private String pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_INFO.TR_ID
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	private String trId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_INFO.TR_VERSION
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	private String trVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_INFO.TR_LEVEL
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	private String trLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_INFO.TR_AREA
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	private String trArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_INFO.TR_TIME
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	private Date trTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_INFO.TR_FLAG
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	private String trFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_INFO.REMARK
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_INFO.PK
	 * @return  the value of TR_INFO.PK
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public String getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_INFO.PK
	 * @param pk  the value for TR_INFO.PK
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setPk(String pk) {
		this.pk = pk == null ? null : pk.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_INFO.TR_ID
	 * @return  the value of TR_INFO.TR_ID
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public String getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_INFO.TR_ID
	 * @param trId  the value for TR_INFO.TR_ID
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setTrId(String trId) {
		this.trId = trId == null ? null : trId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_INFO.TR_VERSION
	 * @return  the value of TR_INFO.TR_VERSION
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public String getTrVersion() {
		return trVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_INFO.TR_VERSION
	 * @param trVersion  the value for TR_INFO.TR_VERSION
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setTrVersion(String trVersion) {
		this.trVersion = trVersion == null ? null : trVersion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_INFO.TR_LEVEL
	 * @return  the value of TR_INFO.TR_LEVEL
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public String getTrLevel() {
		return trLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_INFO.TR_LEVEL
	 * @param trLevel  the value for TR_INFO.TR_LEVEL
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setTrLevel(String trLevel) {
		this.trLevel = trLevel == null ? null : trLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_INFO.TR_AREA
	 * @return  the value of TR_INFO.TR_AREA
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public String getTrArea() {
		return trArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_INFO.TR_AREA
	 * @param trArea  the value for TR_INFO.TR_AREA
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setTrArea(String trArea) {
		this.trArea = trArea == null ? null : trArea.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_INFO.TR_TIME
	 * @return  the value of TR_INFO.TR_TIME
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public Date getTrTime() {
		return trTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_INFO.TR_TIME
	 * @param trTime  the value for TR_INFO.TR_TIME
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setTrTime(Date trTime) {
		this.trTime = trTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_INFO.TR_FLAG
	 * @return  the value of TR_INFO.TR_FLAG
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public String getTrFlag() {
		return trFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_INFO.TR_FLAG
	 * @param trFlag  the value for TR_INFO.TR_FLAG
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setTrFlag(String trFlag) {
		this.trFlag = trFlag == null ? null : trFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_INFO.REMARK
	 * @return  the value of TR_INFO.REMARK
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_INFO.REMARK
	 * @param remark  the value for TR_INFO.REMARK
	 * @mbggenerated  Mon Jul 06 09:40:43 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}