package com.whty.cms.tspm.pojo;

import java.util.Date;

public class TrOperationHisKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_OPERATION_HIS.OPERATION_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private Date operationTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TR_OPERATION_HIS.TR_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	private String trId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_OPERATION_HIS.OPERATION_TIME
	 * @return  the value of TR_OPERATION_HIS.OPERATION_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public Date getOperationTime() {
		return operationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_OPERATION_HIS.OPERATION_TIME
	 * @param operationTime  the value for TR_OPERATION_HIS.OPERATION_TIME
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TR_OPERATION_HIS.TR_ID
	 * @return  the value of TR_OPERATION_HIS.TR_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public String getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TR_OPERATION_HIS.TR_ID
	 * @param trId  the value for TR_OPERATION_HIS.TR_ID
	 * @mbggenerated  Mon Jun 08 10:17:37 CST 2015
	 */
	public void setTrId(String trId) {
		this.trId = trId == null ? null : trId.trim();
	}
}